# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieReview-Task' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieReview-Task
  # Networkit pod 
  pod 'Alamofire'
  # Mapping the json response
  pod 'ObjectMapper'
  # PromiseKit to manage the promise of alamofire
  pod 'PromiseKit'
  # Easy manager to image
  pod 'AlamofireImage'
end
