# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test-alamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #Create the connection with the endpoints
  pod 'Alamofire'
  #ObjectMapper is a way to parse the json
  pod 'ObjectMapper'
  #PromiseKit Creator of promise for calls 
  pod 'PromiseKit'
  #AlamofireImage helps with the images in the endpoint
  pod 'AlamofireImage'
  # Pods for test-alamofire

end
